CREATE TABLE IF NOT EXISTS Transaction (
    ID UUID PRIMARY KEY,
    Client UUID REFERENCES Client(ID) ON DELETE CASCADE,
    Album UUID REFERENCES Album(ID) ON DELETE CASCADE,
    Amount NUMERIC(10, 2) NOT NULL,
    Timestamp TIMESTAMPTZ NOT NULL
);
